### ISSUE TITLE
3.2 相关问题

### ISSUE THREAD

**Issue by Gragle526** [SamuelGong/Lotto-doc#1]
您好我在试图复现您的论文代码至3.2的时候发现我需要在命令里上传配置文件。
![image](https://github.com/user-attachments/assets/4b32da78-6f7a-496d-af4c-7104c2c001e5)
但是我没有在您的代码中找到配置文件的相关示例或者其他有关写配置文件的指导。我想请问我该如何写一份配置文件。

**Comment by SamuelGong** [comment]
Thank you for reaching out. With the most recent commit bed74300a5d9cb3fd88ec70e8d6cca2949ddc724,  we have added example configuration files in the folder [exploration/config_examples](exploration/config_examples), which may assist you in reproducing our main results.

---

感谢您的联系。在最新的提交 bed74300a5d9cb3fd88ec70e8d6cca2949ddc724 中，我们在 [exploration/config_examples](exploration/config_examples) 文件夹添加了一些示例配置文件，也许对您复现我们的主要结果有帮助。
